<h1 align=center>R BASICS</h1> 

<h2 align=center> Simple Math in R </h2>

In [5]:
130+121

[1] 251

In [7]:
251/60 # hours Converted into hours

[1] 4.183333

In [8]:
x <- 130+121

In [9]:
x

[1] 251

In [11]:
y <- x / 60
y

[1] 4.183333

In [12]:
x <- x/60
x

[1] 4.183333

In [13]:
total <- 130+121
total

[1] 251

In [14]:
total_hr <- total/60
total_hr

[1] 4.183333

In [15]:
total_hr <- (130+121)/60
total_hr

[1] 4.183333

<h2 align=center>Vectors in R</h2>

In [16]:
c(81,125)/60  # c function for combine

[1] 1.350000 2.083333

In [18]:
ratings <- c(81,125)
ratings/60

[1] 1.350000 2.083333

In [19]:
c(1, 2, 3, 4, 5, 6, 7, 8, 9, 10)
c(1:10)

[1]  1  2  3  4  5  6  7  8  9 10

[1]  1  2  3  4  5  6  7  8  9 10

In [20]:
c(1:10)

[1]  1  2  3  4  5  6  7  8  9 10

<h2 align=center>String in R</h2>

In [21]:
movie <- "Toy Story"
movie

[1] "Toy Story"

In [22]:
genres <- c("Animation", "Comedy", "Biography", "Horror", "Romance", "Sci-fi")
genres

[1] "Animation" "Comedy"    "Biography" "Horror"    "Romance"   "Sci-fi"

<h2 align=center>Vectors And Factors<\h2>

<img src = "https://ibm.box.com/shared/static/6kr8sg0n6pc40zd1xn6hjhtvy3k7cmeq.png" width = 90% align="left">

<h2 align=center>VECTORS</h2>

In [26]:
release_yr <- c(1985, 1999, 2015, 1964)
release_yr

[1] 1985 1999 2015 1964

In [29]:
# Create genre vector and assign values to it 
titles <- c("Toy Story", "Akira", "The Breakfast Club")
titles

[1] "Toy Story"          "Akira"              "The Breakfast Club"

In [30]:
# Logical vectors(TRUE,FALSE OR T ,F)
titles == 'Akira'

[1] FALSE  TRUE FALSE

<h2 align=center>Vector Operations<\h2>

In [31]:
# Adding element
release_yr <- c(release_yr,2016:2018)
release_yr

[1] 1985 1999 2015 1964 2016 2017 2018

In [32]:
# Length of vector
length(release_yr)

[1] 7


### Head and Tail of vector


In [33]:
head(release_yr)  # show First six element

[1] 1985 1999 2015 1964 2016 2017

In [34]:
head(release_yr, n = 2)  # shows first two element

[1] 1985 1999

In [35]:
tail(release_yr)  # shows last six element

[1] 1999 2015 1964 2016 2017 2018

In [36]:
tail(release_yr,2)  # shows last two element

[1] 2017 2018

### Sorting a Vector

In [37]:
sort(release_yr)

[1] 1964 1985 1999 2015 2016 2017 2018

In [38]:
sort(release_yr, decreasing=T)

[1] 2018 2017 2016 2015 1999 1985 1964

In [40]:
min(release_yr)
max(release_yr)

[1] 1964

[1] 2018

### Average of Numbers

In [41]:
cost_2014 <- c(8.6,8.5,8.1)

# sum results in the sum of all elements in the vector
avg_cost_2014 <- sum(cost_2014)/3
avg_cost_2014

[1] 8.4

In [43]:
# MEAN
mean_cost_2014 <- mean(cost_2014)
mean_cost_2014

[1] 8.4

### Giving Names to values in a vector

In [46]:
#Creating a year vector
release_year        <- c(1985,                 1999,  
                         2010,           2002)

#Assigning names
names(release_year) <- c("The Breakfast Club", "American Beauty",
                         "Black Swan", "Chicago")

release_year

The Breakfast Club    American Beauty         Black Swan            Chicago 
              1985               1999               2010               2002

In [49]:
release_year[c("American Beauty","Chicago")]

American Beauty         Chicago 
           1999            2002

In [50]:
#adding a number in year
release_year[1] + 100 #adding 100 to the first item changes the year

The Breakfast Club 
              2085

In [51]:
# retrieve the names of the vector using names()
names(release_year)[1:3]

[1] "The Breakfast Club" "American Beauty"    "Black Swan"

### Summarizing Vectors

In [52]:
summary(cost_2014)

   Min. 1st Qu.  Median    Mean 3rd Qu.    Max. 
   8.10    8.30    8.50    8.40    8.55    8.60 



### Using Logical operator On Vectors


In [54]:
# Logical comparision
movie_year <- 1997
movie_year > 2000

[1] FALSE

In [55]:
# Logical comparision between various items
movies_years <- c(1998, 2010, 2016)
movies_years > 2014

[1] FALSE FALSE  TRUE

In [56]:
movies_years == 2015 # is equal to 2015?

[1] FALSE FALSE FALSE

In [57]:
movies_years != 2015

[1] TRUE TRUE TRUE

### Subsetting Vector

In [60]:
movie_years <- c(1985, 1999, 2002, 2010,2012)
movie_years

[1] 1985 1999 2002 2010 2012

In [61]:
#To retrieve the second item
movie_years[2]

[1] 1999

In [62]:
#To retrieve the third element
movie_years[3]

[1] 2002

In [63]:
#if you want to retrieve multiple items, you can pass in a vector:
movie_years[c(1:3)]

[1] 1985 1999 2002

In [64]:
movie_years[c(1,3)]

[1] 1985 2002

#### Retrieving a vector without some of its items

In [66]:
titles <- c("Black Swan","Jumanji","City of God","Toy Story","Casino")
titles[-1]

[1] "Jumanji"     "City of God" "Toy Story"   "Casino"

In [67]:
new_titles <- titles[-1] #removes "Black Swan", the first item and rename
new_titles

[1] "Jumanji"     "City of God" "Toy Story"   "Casino"

#### Missing Values

In [68]:
age_restric <- c(14, 12, 10, NA, 18, NA)
age_restric

[1] 14 12 10 NA 18 NA

In [69]:
is.na(age_restric) # Check if NA

[1] FALSE FALSE FALSE  TRUE FALSE  TRUE

In [70]:
!is.na(2) # Check if not NA

[1] TRUE

### Subsetting vectors based on a logical condition

In [71]:
release_year > 2000

The Breakfast Club    American Beauty         Black Swan            Chicago 
             FALSE              FALSE               TRUE               TRUE

In [72]:
release_year[movie_years > 2000] 
#returns a vector for elements that returned TRUE for the condition

Black Swan    Chicago       <NA> 
      2010       2002         NA

In [73]:
release_year
release_year[c(T, F, F, F)] #returns the values that are TRUE

The Breakfast Club    American Beauty         Black Swan            Chicago 
              1985               1999               2010               2002

The Breakfast Club 
              1985

<center><h2>Factors</h2></center>

In [75]:
genre_vector <- c("Comedy", "Animation", "Crime", "Comedy", "Animation")
genre_vector

[1] "Comedy"    "Animation" "Crime"     "Comedy"    "Animation"

In [79]:
genre_fact <- as.factor(genre_vector)
levels(genre_fact)

[1] "Animation" "Comedy"    "Crime"

### Summarizing Factors

In [80]:
summary(genre_fact)

Animation    Comedy     Crime 
        2         2         1

In [82]:
sort(summary(genre_fact))

Crime Animation    Comedy 
        1         2         2

### Ordered factors

In [83]:
movie_length <- c("Very Short", "Short", "Medium","Short", "Long",
                        "Very Short", "Very Long")
movie_length

[1] "Very Short" "Short"      "Medium"     "Short"      "Long"      
[6] "Very Short" "Very Long"

In [85]:
movie_length_ordered <- factor(movie_length, ordered = TRUE,
                              level = c('Very Short','Short','Long','Very Long'))
movie_length_ordered

[1] Very Short Short      <NA>       Short      Long       Very Short Very Long 
Levels: Very Short < Short < Long < Very Long

In [86]:
summary(movie_length_ordered)

Very Short      Short       Long  Very Long       NA's 
         2          2          1          1          1



<h1 align=center>ARRAYS & MATRICES</h1> 




### Let's create a 4 x 3 array (4 rows, 3 columns)

In [87]:
#lets first create a vector of nine movies
movie_vector <- c("Akira", "Toy Story", "Room", "The Wave", "Whiplash",
                  "Star Wars", "The Ring", "The Artist", "Jumanji")
movie_vector

[1] "Akira"      "Toy Story"  "Room"       "The Wave"   "Whiplash"  
[6] "Star Wars"  "The Ring"   "The Artist" "Jumanji"

In [88]:
movie_array <- array(movie_vector, dim = c(4,3))
movie_array

[,1]      [,2]       [,3]     
[1,] Akira     Whiplash   Jumanji  
[2,] Toy Story Star Wars  Akira    
[3,] Room      The Ring   Toy Story
[4,] The Wave  The Artist Room

### Array Indexing

In [90]:
movie_array

[,1]      [,2]       [,3]     
[1,] Akira     Whiplash   Jumanji  
[2,] Toy Story Star Wars  Akira    
[3,] Room      The Ring   Toy Story
[4,] The Wave  The Artist Room

In [92]:
movie_array[1,2] #[row,column]

movie_array[1,-2] # []

[1] "Whiplash"

[1] "Akira"   "Jumanji"

In [95]:
movie_array[1,]

movie_array[,2]

dim(movie_array)

[1] "Akira"    "Whiplash" "Jumanji"

[1] "Whiplash"   "Star Wars"  "The Ring"   "The Artist"

[1] 4 3

In [2]:
length_vector <- c(125, 81, 118, 81, 106, 121, 95, 100, 104)
length_array <- array(length_vector, dim = c(3,3))
length_array

[,1] [,2] [,3]
[1,] 125   81   95 
[2,]  81  106  100 
[3,] 118  121  104

In [3]:
length_array + 5 # added in numerical only

[,1] [,2] [,3]
[1,] 130   86  100 
[2,]  86  111  105 
[3,] 123  126  109

In [4]:
movie_array + 5 #not added in catogorical

ERROR: Error in eval(expr, envir, enclos): object 'movie_array' not found


### Using Logical Condition to subset Array

In [5]:
# Movies less than 2 hrs
mask_array <- length_array > 120
mask_array

[,1]  [,2]  [,3] 
[1,]  TRUE FALSE FALSE
[2,] FALSE FALSE FALSE
[3,] FALSE  TRUE FALSE

In [9]:
# from above subset the movie
x_vector <- c("Akira", "Toy Story", "Room", "The Wave", "Whiplash",
              "Star Wars", "The Ring", "The Artist", "Jumanji")
x_array <- array(x_vector, dim= c(3,3))
                 
x_array[mask_array]

[1] "Akira"     "Star Wars"

#                           Matrix

In [13]:
# Create metrix
movie_matrix <- matrix(x_vector, nrow= 3, ncol=3)
movie_matrix

[,1]      [,2]      [,3]      
[1,] Akira     The Wave  The Ring  
[2,] Toy Story Whiplash  The Artist
[3,] Room      Star Wars Jumanji

### Accessing element of  matrix

In [15]:

movie_matrix[1,1] 

#the elements from rows 2 to 3, and from columns 1 to 2.
movie_matrix[2:3, 1:2]  # [rows,columns]

[1] "Akira"

[,1]      [,2]     
[1,] Toy Story Whiplash 
[2,] Room      Star Wars

### Concatenation Function

In [17]:
upcoming_movie <- c("Fast and Furious 8", "xXx: Return of Xander Cage",
                    "Suicide Squad")
new_vector <- c(x_vector, upcoming_movie)
new_vector

[1] "Akira"                      "Toy Story"                 
 [3] "Room"                       "The Wave"                  
 [5] "Whiplash"                   "Star Wars"                 
 [7] "The Ring"                   "The Artist"                
 [9] "Jumanji"                    "Fast and Furious 8"        
[11] "xXx: Return of Xander Cage" "Suicide Squad"

# LIST AND DATAFRAME IN R

In [18]:
movie <- list('Toy Story', 1995, c('Animation','Adventure','Comedy'))
movie

[[1]]
[1] "Toy Story"

[[2]]
[1] 1995

[[3]]
[1] "Animation" "Adventure" "Comedy"

### Accessing items in a list

In [20]:
movie[2]
movie[2:3] # slicing

[[1]]
[1] 1995

[[1]]
[1] 1995

[[2]]
[1] "Animation" "Adventure" "Comedy"

### Named List

In [21]:
movie <- list(name= 'Toy Story',
             year = 1995,
             genre= c('Animation','Adventure','Comedy'))
movie

$name
[1] "Toy Story"

$year
[1] 1995

$genre
[1] "Animation" "Adventure" "Comedy"

In [22]:
movie$genre

[1] "Animation" "Adventure" "Comedy"

In [23]:
movie['genre']

$genre
[1] "Animation" "Adventure" "Comedy"

In [24]:
class(movie$name)
class(movie$foreign)

[1] "character"

[1] "NULL"

### Adding, modifing and removing items

In [26]:
movie[['age']] <- 5
movie

$name
[1] "Toy Story"

$year
[1] 1995

$genre
[1] "Animation" "Adventure" "Comedy"   

$age
[1] 5

In [27]:
movie[['age']]<- 6
movie

$name
[1] "Toy Story"

$year
[1] 1995

$genre
[1] "Animation" "Adventure" "Comedy"   

$age
[1] 6

In [29]:
movie[['age']]<- NULL
movie

$name
[1] "Toy Story"

$year
[1] 1995

$genre
[1] "Animation" "Adventure" "Comedy"

### Concatenating List 

In [31]:
# We split our previous list in two sublists
movie_part1 <- list(name = "Toy Story")
movie_part2 <- list(year = 1995, genre = c("Animation",
                                           "Adventure", "Comedy"))
movie_concatenated <- c(movie_part1, movie_part2)
movie_concatenated

$name
[1] "Toy Story"

$year
[1] 1995

$genre
[1] "Animation" "Adventure" "Comedy"

## DataFrame

In [14]:
movies <- data.frame(name = c("Toy Story", "Akira", "The Breakfast Club", "The Artist",
                              "Modern Times", "Fight Club", "City of God", "The Untouchables"),
                    year = c(1995, 1998, 1985, 2011, 1936, 1999, 2002, 1987),
                    stringsAsFactors=F)
movies

name               year
1 Toy Story          1995
2 Akira              1998
3 The Breakfast Club 1985
4 The Artist         2011
5 Modern Times       1936
6 Fight Club         1999
7 City of God        2002
8 The Untouchables   1987

In [33]:
movies$name

[1] "Toy Story"          "Akira"              "The Breakfast Club"
[4] "The Artist"         "Modern Times"       "Fight Club"        
[7] "City of God"        "The Untouchables"

In [34]:
movies[1]

name              
1 Toy Story         
2 Akira             
3 The Breakfast Club
4 The Artist        
5 Modern Times      
6 Fight Club        
7 City of God       
8 The Untouchables

In [35]:
movies[2:3,1:2]

name               year
2 Akira              1998
3 The Breakfast Club 1985

In [37]:
str(movies)

'data.frame':	8 obs. of  2 variables:
 $ name: chr  "Toy Story" "Akira" "The Breakfast Club" "The Artist" ...
 $ year: num  1995 1998 1985 2011 1936 ...


In [38]:
class(movies$year)

[1] "numeric"

In [39]:
movies[1,2] #[Row,column]

[1] 1995

In [40]:
head(movies) # First five

name               year
1 Toy Story          1995
2 Akira              1998
3 The Breakfast Club 1985
4 The Artist         2011
5 Modern Times       1936
6 Fight Club         1999

In [41]:
tail(movies) # Last five

name               year
3 The Breakfast Club 1985
4 The Artist         2011
5 Modern Times       1936
6 Fight Club         1999
7 City of God        2002
8 The Untouchables   1987

In [44]:
length(movies)

[1] 2

In [45]:
# New Column added
movies['length'] <- c(81, 125, 97, 100, 87, 139, 130, 119)
movies

name               year length
1 Toy Story          1995  81   
2 Akira              1998 125   
3 The Breakfast Club 1985  97   
4 The Artist         2011 100   
5 Modern Times       1936  87   
6 Fight Club         1999 139   
7 City of God        2002 130   
8 The Untouchables   1987 119

In [52]:
# New Movie(row) added
movies <- rbind(movies, c(name='Dr.Strangelove', year=1964, length=94))
movies

name               year length
1  Toy Story          1995 81    
2  Akira              1998 125   
3  The Breakfast Club 1985 97    
4  The Artist         2011 100   
5  Modern Times       1936 87    
6  Fight Club         1999 139   
7  City of God        2002 130   
8  The Untouchables   1987 119   
9  Dr.Strangelove     1964 94    
10 Dr.Strangelove     1964 94    
11 Dr.Strangelove     1964 94

In [55]:
# To remove Row
movies <- movies[-10,]
movies

name               year length
1  Toy Story          1995 81    
2  Akira              1998 125   
3  The Breakfast Club 1985 97    
4  The Artist         2011 100   
5  Modern Times       1936 87    
6  Fight Club         1999 139   
7  City of God        2002 130   
8  The Untouchables   1987 119   
9  Dr.Strangelove     1964 94    
11 Dr.Strangelove     1964 94

In [57]:
# TO remove column
movies[['length']] <- NULL
movies

name               year
1  Toy Story          1995
2  Akira              1998
3  The Breakfast Club 1985
4  The Artist         2011
5  Modern Times       1936
6  Fight Club         1999
7  City of God        2002
8  The Untouchables   1987
9  Dr.Strangelove     1964
11 Dr.Strangelove     1964

# LOOPS AND CONDITIONS

In [58]:
data()

Data sets in package 'datasets':

AirPassengers           Monthly Airline Passenger Numbers 1949-1960
BJsales                 Sales Data with Leading Indicator
BJsales.lead (BJsales)
                        Sales Data with Leading Indicator
BOD                     Biochemical Oxygen Demand
CO2                     Carbon Dioxide Uptake in Grass Plants
ChickWeight             Weight versus age of chicks on different diets
DNase                   Elisa assay of DNase
EuStockMarkets          Daily Closing Prices of Major European Stock
                        Indices, 1991-1998
Formaldehyde            Determination of Formaldehyde
HairEyeColor            Hair and Eye Color of Statistics Students
Harman23.cor            Harman Example 2.3
Harman74.cor            Harman Example 7.4
Indometh                Pharmacokinetics of Indomethacin
InsectSprays            Effectiveness of Insect Sprays
JohnsonJohnson          Quarterly Earnings per Johnson & Johnson Share
LakeHuron               Level of Lake Huron 1875-1972
LifeCycleSavings        Intercountry Life-Cycle Savings Data
Loblolly                Growth of Loblolly pine trees
Nile                    Flow of the River Nile
Orange                  Growth of Orange Trees
OrchardSprays           Potency of Orchard Sprays
PlantGrowth             Results from an Experiment on Plant Growth
Puromycin               Reaction Velocity of an Enzymatic Reaction
Seatbelts               Road Casualties in Great Britain 1969-84
Theoph                  Pharmacokinetics of Theophylline
Titanic                 Survival of passengers on the Titanic
ToothGrowth             The Effect of Vitamin C on Tooth Growth in
                        Guinea Pigs
UCBAdmissions           Student Admissions at UC Berkeley
UKDriverDeaths          Road Casualties in Great Britain 1969-84
UKgas                   UK Quarterly Gas Consumption
USAccDeaths             Accidental Deaths in the US 1973-1978
USArrests               Violent Crime Rates by US State
USJudgeRatings          Lawyers' Ratings of State Judges in the US
                        Superior Court
USPersonalExpenditure   Personal Expenditure Data
UScitiesD               Distances Between European Cities and Between
                        US Cities
VADeaths                Death Rates in Virginia (1940)
WWWusage                Internet Usage per Minute
WorldPhones             The World's Telephones
ability.cov             Ability and Intelligence Tests
airmiles                Passenger Miles on Commercial US Airlines,
                        1937-1960
airquality              New York Air Quality Measurements
anscombe                Anscombe's Quartet of 'Identical' Simple Linear
                        Regressions
attenu                  The Joyner-Boore Attenuation Data
attitude                The Chatterjee-Price Attitude Data
austres                 Quarterly Time Series of the Number of
                        Australian Residents
beaver1 (beavers)       Body Temperature Series of Two Beavers
beaver2 (beavers)       Body Temperature Series of Two Beavers
cars                    Speed and Stopping Distances of Cars
chickwts                Chicken Weights by Feed Type
co2                     Mauna Loa Atmospheric CO2 Concentration
crimtab                 Student's 3000 Criminals Data
discoveries             Yearly Numbers of Important Discoveries
esoph                   Smoking, Alcohol and (O)esophageal Cancer
euro                    Conversion Rates of Euro Currencies
euro.cross (euro)       Conversion Rates of Euro Currencies
eurodist                Distances Between European Cities and Between
                        US Cities
faithful                Old Faithful Geyser Data
fdeaths (UKLungDeaths)
                        Monthly Deaths from Lung Diseases in the UK
freeny                  Freeny's Revenue Data
freeny.x (freeny)       Freeny's Revenue Data
freeny.y (freeny)       Freeny's Revenue Data
infert                  Infertility after Spontaneous

In [ ]:
# Control statements : o control what pieces of the program are to be executed at certain times. 
# Conditional statements and Loops are the control statements that are able to change the execution flow.


### Conditional Statements

### If Statements

In [62]:
movie_yr = 2002
if(movie_yr > 2000){
    print("Movie year is greater than 2000")
}

[1] "Movie year is greater than 2000"


In [65]:
movie_yr <- readline("Please enter no.")
if(movie_yr > 2000){
    print("Movie year is greater than 2000")
}else{
    print("Movie year is not greater than 2000")
}

Please enter no. 2002


[1] "Movie year is greater than 2000"


In [72]:
# By using comparision and Logical operator
movie_yr = 1997
if (movie_yr < 2000 & movie_yr > 1990){
    print("Movie year between 2000 and 1990")
}

if (movie_yr > 2010 | movie_yr < 2000){
    print("Movie year is not between 2010 and 2000")
}

[1] "Movie year between 2000 and 1990"
[1] "Movie year is not between 2010 and 2000"


### Subset

In [75]:
decade = "recent"

if (decade == "recent"){
    subset(movies,year >= 2000)
    ## Subset the dataset to include only movies after year 2000.
    }else{
    # If not..# Subset the dataset to include only movies before 2000.
    subset(movies, year < 2000)
}

name        year
4 The Artist  2011
7 City of God 2002

In [83]:
decade = 'new'
if(decade == 'new'){
    subset(movies,year >= 1990)
}else{
    subset(movies, year > 1990)
}

name        year
1 Toy Story   1995
2 Akira       1998
4 The Artist  2011
6 Fight Club  1999
7 City of God 2002

### Loops 

In [3]:
# FOR Loops
# execute this once for every row in my dataset,column
years <- movies['year']

for (val in years){
    print(val)
}

[1] 1995 1998 1985 2011 1936 1999 2002 1987


In [17]:
year <- movies['year']
for (years in year){
    if (years > 2000){
        print('Movie is Recent')
    } else {
        print('Movie is old')
    }
}

Warning message in if (years > 2000) {:
"the condition has length > 1 and only the first element will be used"

[1] "Movie is old"


In [10]:
# While Loop
# if we don't know when we want to stop the loop?
# Creating start point
iteration = 1
while (iteration <= 5){
    print(c('This is iteration number :',as.character(iteration)))
    print(movies[iteration,]$name)
    iteration = iteration + 1
}


[1] "This is iteration number :" "1"                         
[1] "Toy Story"
[1] "This is iteration number :" "2"                         
[1] "Akira"
[1] "This is iteration number :" "3"                         
[1] "The Breakfast Club"
[1] "This is iteration number :" "4"                         
[1] "The Artist"
[1] "This is iteration number :" "5"                         
[1] "Modern Times"


In [ ]:
iteration = movies['year']
while(iteration <= 2000){
    print('Movie is old')
    iteration = movies['year']
}

### Applying Functions to Vectors

In [11]:
# First, we create a vector...
my_list <- c(10,12,15,19,25,33)

# ...we can try adding two to all the values in that vector.
my_list + 2

# Or maybe even exponentiating them by two.
my_list ** 2

# We can also sum two vectors element-wise!
my_list + my_list

[1] 12 14 17 21 27 35

[1]  100  144  225  361  625 1089

[1] 20 24 30 38 50 66

# WRITING YOUR OWN CUSTOM FUNCTIONS IN R

# two types of functions :

1.Pre-defined functions

2.User defined functions

In [1]:
ratings <- c(8.7, 6.9, 8.5)
mean(ratings)

[1] 8.033333

In [2]:
sort(ratings)

[1] 6.9 8.5 8.7

In [3]:
sort(ratings,decreasing = T)

[1] 8.7 8.5 6.9

### User Define Function

In [8]:
printHelloWorld <- function(){
    print('Hello World')
}
printHelloWorld()

[1] "Hello World"


In [9]:
add <- function(x,y){
    x+y
}
add(3,4)

[1] 7

In [ ]:
function(arguments){
    Do something
    Do something
    return(some_output)
}

### Explicitly returning outputs in user-defined functions

In [12]:
add <- function(x,y){
    return(x+y)
}
add(3,4)

[1] 7

### Using IF/ELSE statements in functions

In [ ]:
isGoodRating <- function(rating, threashold = 7){
    if (rating < threahold){
        return('NO')
    } else {
        return('YES')
    }
}
isGoodRating(6)
isGoodRating(9.5)

In [ ]:
isGoodRating(8,threashold=8.5)
isGoodRating(8. 8.5)

In [ ]:
my_data <- read.csv("movies-db.csv")
head(my_data)

In [ ]:
akira <- my_data[data$name=='a']